version: '2'

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - database.env

  authoritative:
    build: .
    links:
      - database
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "8080:80"
    env_file:
      - database.env
